name: Verify

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  data:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      - run: mise run test
